### ISSUE TITLE
Where do the grid lines come from?

### ISSUE THREAD

**Issue by orlin** [JohnAlbin/normalize-scss#101]
When I use this module together with Susy I automatically get horizontal lines to guide / debug a vertical rhythm (revealed together with Susy's grid).  Could you point me to how that happens and where the code for it is?

If I include `normalize.css` instead, the lines disappear.  So it must be coming from here...  Unfortunately GitHub doesn't search forked repos yet.

**Comment by JohnAlbin** [comment]
normalize-scss doesn't make vertical rhythm grid lines.

**Comment by strarsis** [comment]
@orlin: Have you imported normalize before or after you define the susy grids?
susy styles must come after the normalize styles - otherwise they could be overridden.

**Comment by JohnAlbin** [comment]
Thanks for the insight @strarsis! I don't use Susy, so I was hoping someone would provide a fix. :)
