### ISSUE TITLE
cant compile scss - error : normalize-font-size() only supports px inputs.

### ISSUE THREAD

**Issue by marioloncarek** [JohnAlbin/normalize-scss#103]
Hello, 

Im using your plugin with import now option, which is including from bower components. When i try to have initial compile of scss i get this error: 

`bower_components\normalize-scss\sass\normalize\_vertical-rhythm.scss
Error: normalize-font-size() only supports px inputs. The typey library is better.
        on line 25 of bower_components/normalize-scss/sass/normalize/_vertical-rhythm.scss
`
And i cant proceed any work. Thanks in advance

**Comment by wsfuller** [comment]
I found this digging through the test directory

https://github.com/JohnAlbin/normalize-scss/blob/master/test/fixtures/variables/font/input.scss

Setting up like:

```
    $base-font-size: 16px;
    $base-line-height: 24px;
    $base-unit: rem;

    $h1-font-size: 2.75 * $base-font-size;
```

This seems to be working as expected. I tend to use `rem` units for all type and previewing in the browser everything is sizing correctly. I tried using Typey and wasn't able to get that working with Normalize. I think the overlaying issue is lack of documentation especially with integrating libraries with no examples.

**Comment by JohnAlbin** [comment]
If you use the default variable values of normalize-scss, Typey works fine with it.

The normalize-scss variables provide rudimentary alterations for fonts. If you want more advanced font styling, don't modify the variables and normalize-scss will output the standard normalization CSS rulesets. You can then use Typey to modify your fonts with separate rules. If you find that normalize-scss’ `html {}` ruleset is too similar to what Typey outputs, you could prevent that normalize-scss rule using `@include normalize($exclude: document)`.

> I tried using Typey and wasn't able to get that working with Normalize.

Speaking of documentation… you provide no way for me to recreate your problem. I can't provide docs on how to prevent integration problems if you don't tell me what integration problems you have.
