### ISSUE TITLE
Upgrade to normalize 7.0.0

### ISSUE THREAD

**Issue by JohnAlbin** [JohnAlbin/normalize-scss#107]
Normalize 7.0.0 is out. https://github.com/necolas/normalize.css/releases

**Comment by garrettw** [comment]
Do you have any thoughts/feelings about whether opinionated rules should be included or not?

**Comment by JohnAlbin** [comment]
I do, actually!

I prefer to fork normalize.css alter the rulesets to match what the particular project needs. That means having a scaffold for rules needed in my project, but not needed in a drop-in-and-forget version of normalize.css. For example, `p { margin: 1.5rem 0 }`

Fortunately, this project a mixin-based version of normalize and a fork-ready version of normalize. So I can keep my opinionated rules in the forks and, in the mixin-based normalize, follow the parent normalize.css project's direction of removing opinionated rules.

**Comment by garrettw** [comment]
What I'm referring to is the rules that version 6 removed and that version 7 is bringing back, due to the difference in vision of the two prior maintainers.

(And on that note, I have to ask: is that debacle the reason for your recent "code of conduct" commits?)

**Comment by JohnAlbin** [comment]
> What I'm referring to is the rules that version 6 removed and that version 7 is bringing back

I'm just following whatever is in their code when deciding what goes in the mixin version of normalize-scss. Other contributers and users have expressed the desire that the default CSS output of the mixin should match the CSS in normalize.css.

And I will keep the opinionated rules that I like in the fork versions.

> And on that note, I have to ask: is that debacle the reason for your recent "code of conduct" commits?

@garrettw Lol. No. It's unrelated to their disagreements. I've been meaning to add one to all my projects and I am finally getting around to adding them.
