### ISSUE TITLE
@import "normalize" is not working

### ISSUE THREAD

**Issue by RunningLat3** [JohnAlbin/normalize-scss#109]
I am using webpack and this is my code for sass-loader:

            {
                test: /\.scss$/,
                use: ExtractTextPlugin.extract({
                    fallback: 'style-loader',
                    use: [
                        {loader:'css-loader'}, 
                        { 
                            loader: 'sass-loader', 
                            options: {
                                includePaths: [
                                    path.join(__dirname, 'node_modules/normalize-scss/sass')
                                ]
                            }
                        }
                    ],
                    publicPath: '../'                    
                })
            }//* sass loader

and app.scss:

@import "normalize" <-- this is not working

**QUICK FIX I DID IS:**

@import "normalize/import-now"

According to your documentation I only needed to do the first one, I am confuse on which is right to do.

Thanks

**Comment by Garfield550** [comment]
``` SCSS
@import 'normalize';
@include normalize();
```

**Comment by JohnAlbin** [comment]
As @Garfield550 pointed out, you missed one of the steps in the docs.

https://github.com/JohnAlbin/normalize-scss#how-to-use-it

**Comment by codepandy** [comment]
how to use it? it so hard to use!!!
