### ISSUE TITLE
Unable to bundle into CSS file using Webpack v2

### ISSUE THREAD

**Issue by wsfuller** [JohnAlbin/normalize-scss#113]
Installed using the provided instructions within the README file but nothing gets bundled into my `app.css`

**Tech:**

- Webpack: 2.2.1
- Nomalize: 7.0.0
- sass-loader: 6.0.2
- style-loader: 0.13.2
- node-sass: 4.5.0
- extract-text-webpack-plugin: 2.0.0
- css-loader: 0.26.2
- postcss-loader: 1.3.3
- postcss-smart-import: 0.6.9
- precss: 1.4.0

`yarn add normalize-scss`

**Webpack Config:**

    rules: [
      {
        test: /\.(s?)css$/,
	use: ExtractTextPlugin.extract({
	fallback: 'style-loader',
	use: ['css-loader', 'resolve-url-loader', 'postcss-loader', 'sass-loader']
      })
    },
    ...
    plugins[
      new ExtractTextPlugin({
        filename: 'app.css',
	allChunks: true
      })
    ]

**index.scss:**

    @import 'normalize';
    @include normalize();

Which returns an error `@import 'normalize'; File to import not found or unreadable: normalize.`

    @import "../node_modules/normalize-scss/sass/normalize";
    @include normalize();

Doesn't bundle anything into my `app.css`

Sanity check against `hint.css`

    @import "../node_modules/hint.css/src/hint";

This bundles hint.css as expected but nothing for normalize.

What am I missing to get this modules to bundle correctly? Looking over **Approach 2** and looks like I'm including the path, have newest version, including `normalize()`, and another dependency is bundling just fine.

**Comment by JohnAlbin** [comment]
If you've configured webpack correctly, then `@include normalize();` will output the default CSS rulesets.

Unfortunately, I can't help with your webpack config.
