### ISSUE TITLE
line-height value

### ISSUE THREAD

**Issue by kermage** [JohnAlbin/normalize-scss#114]
Isn't it best to use a unitless value in normalizing line heights?

**Comment by JohnAlbin** [comment]
The normalize-scss _does_ use unitless values. The default output of the mixin is a part of our test suite and I've confirmed there are no units on the line height.
https://github.com/JohnAlbin/normalize-scss/blob/master/test/fixtures/import-now/output.css

If you set the `$normalize-vertical-rhythm` variable, then you are specifically asking for line heights with units. https://zellwk.com/blog/why-vertical-rhythms/

> Isn't it best to use a unitless value in normalizing line heights?

Many think so. http://meyerweb.com/eric/thoughts/2006/02/08/unitless-line-heights/ But it depends on your design criteria. I don't want to prevent either design choice.
