### ISSUE TITLE
Remove unneeded legacy code (arg / option)

### ISSUE THREAD

**Issue by Ne-Ne** [JohnAlbin/normalize-scss#119]
Is there any current means of only importing code via mixin that meets certain browser requirements.

An example of is shown below, I have no need for it as I have browser support 11+. Is there an argument or logic that will split out this unneeded code?

https://github.com/JohnAlbin/normalize-scss/blob/90c5d18e601f079c4e514ded011a14b479513784/sass/normalize/_normalize-mixin.scss#L196-L216

Many thanks,
Neil

**Comment by aj1991** [comment]
+ 1 :)

**Comment by artursopelnik** [comment]
+1

**Comment by JohnAlbin** [comment]
Normalize-scss used to have code that allowed you to pick specific versions of browsers, but it made the code base more complicated. And after Microsoft dropped support for IE8 and earlier, the extra code was too much trouble just to trim 5-6 harmless rulesets.

If you wish to use the `$support-for` variable, you can switch back to the 5.x branch. https://github.com/JohnAlbin/normalize-scss/tree/5.0.4

```
$support-for: (
  ie:  11, // Support IE 11
  '*': -4 // Support the last 4 versions of all other browsers.
);
```
