### ISSUE TITLE
 864px*px isn't a valid CSS value

### ISSUE THREAD

**Issue by realchrisolin** [JohnAlbin/normalize-scss#127]
Trying to import normalize into a Jekyll theme. I have included `@import "normalize/import-now"` in `assets/main.scss` and receive the following error when trying to build the Jekyll site.  

```
Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/main.scss':
                    864px*px isn't a valid CSS value. on line 16
jekyll 3.6.2 | Error:  864px*px isn't a valid CSS value. on line 16
```

The error is a bit misleading because main.scss is less than 10 lines long. Logic dictates it's coming from one of the files being imported. I don't encounter this issue if I drop `@import "normalize/import-now"`.  I've looked through the normalize .scss files being imported, but I cannot figure out which file/line is causing this. The directory structure looks like:

```
(personal) [pty4] ~/jekyll-theme (branch:master) » ll -R _sass
_sass:
total 13K
-rwxr-xr-x+ 1 colin None  105 Jan 23 15:32 _normalize.scss
drwxr-xr-x+ 1 colin None    0 Jan 23 15:00 theme
-rwxr-xr-x+ 1 colin None 1.2K Jan 23 12:26 theme.scss
drwxr-xr-x+ 1 colin None    0 Jan 23 15:55 normalize

_sass/theme:
total 16K
-rwxr-xr-x+ 1 colin None 3.5K Jan 23 12:18 _base.scss
-rwxr-xr-x+ 1 colin None 4.3K Jan 23 12:18 _layout.scss
-rwxr-xr-x+ 1 colin None 3.2K Jan 23 12:18 _syntax-highlighting.scss

_sass/normalize:
total 25K
-rw-rw-r--+ 1 colin None  260 Jan 23 15:32 _import-now.scss
-rw-rw-r--+ 1 colin None  15K Jan 23 15:55 _normalize-mixin.scss
-rw-rw-r--+ 1 colin None 1.3K Jan 23 15:32 _variables.scss
-rw-rw-r--+ 1 colin None 1.9K Jan 23 15:32 _vertical-rhythm.scss
```

**Comment by JohnAlbin** [comment]
Where in your code are you setting a variable to `864px`?

**Comment by realchrisolin** [comment]
Nowhere. I believe that value is being generated by the normalize sass code and I have no previous experience debugging or troubleshooting it. I've worked around this issue by using vanilla normalize.css, but I would like to ultimately use this version.

**Comment by garrettw** [comment]
I would guess that you may have set custom values for the included variables. Can you post the contents of your `main.scss`?

**Comment by JasonFoglia** [comment]
Here is a codepen of the exact issue.

https://codepen.io/JasonFog/pen/MMNLRK

**Comment by garrettw** [comment]
Yep, one of the factors must be unitless.
