### ISSUE TITLE
Request for placeholder normalization

### ISSUE THREAD

**Issue by sascha-haenlein** [JohnAlbin/normalize-scss#136]
If you use placeholder in input fields the style differs in Firefox because they manipulate the opacity.
Could you please add opacity and color to be reset?

I need to do this to get equal results:
*::placeholder {
      color: gray;
      opacity: 1;
}

**Comment by garrettw** [comment]
This issue has already been raised by [multiple people](https://github.com/necolas/normalize.css/issues?utf8=%E2%9C%93&q=is%3Aissue+placeholder). You might read through some of those threads to see what the outcome was.
