### ISSUE TITLE
dart-sass: deprecation warning: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

### ISSUE THREAD

**Issue by iruzevic** [JohnAlbin/normalize-scss#148]
## Expected behavior
No deprecation warnings in the console.

## Actual behavior
dart-sass (v 1.34.0) is reporting deprecation warnings.

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($value, $relative-to)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
16 │     @return ($value / $relative-to) * 1em;
   │              ^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/normalize-scss/sass/normalize/_vertical-rhythm.scss 16:14  normalize-rhythm()
    node_modules/normalize-scss/sass/normalize/_vertical-rhythm.scss 27:14  normalize-font-size()
    node_modules/normalize-scss/sass/normalize/_normalize-mixin.scss 108:7  normalize()

**Comment by Andreas-Schoenefeldt** [comment]
Recommendation: `math.div($value, $relative-to)`

**Comment by iruzevic** [comment]
I see that there wasn't any activity on this repo un the last 4 years so I think this will not be resolved any time soon

**Comment by Andreas-Schoenefeldt** [comment]
jea, a classical dead repository - I'll take the current files into our code repository then and drop the  dependency

**Comment by sandcastle** [comment]
@JohnAlbin - are you still maintaining this package/repo?

**Comment by strarsis** [comment]
Or is there an official fork of this repository I missed and don't know of?

**Comment by Zeng95** [comment]
Please merge the kippsterr's branch @JohnAlbin

**Comment by JohnAlbin** [comment]
Fixed in `main` thanks to the PRs!
