### ISSUE TITLE
Unprotected license comment

### ISSUE THREAD

**Issue by strarsis** [JohnAlbin/normalize-scss#41]
The license comment (for MIT license) is not protected:
````
/* normalize-scss 3.0.3+normalize.3.0.3 | MIT/GPLv2 License | bit.ly/normalize-scss */
````

The exclamation mark is missing.

Here the license comment of the original normalize CSS 
(https://github.com/necolas/normalize.css/blob/3.0.3/normalize.css#L1)
````
/*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */
````

This is important, because CSS minifiers (e.g. csswring) will strip a normal comment away, 
and this license notice won't appear in the CSS file being published.

Thank you and
With best regards

**Comment by JohnAlbin** [comment]
Thanks, @strarsis!
