### ISSUE TITLE
Eyeglass import issues

### ISSUE THREAD

**Issue by strarsis** [JohnAlbin/normalize-scss#44]
I try to @import normalize or normalize/import-now, 
but eyeglass alone doesn't seem to be able to pick it up.

I prepared a test repo so one can debug it directly:
https://github.com/strarsis/normalize-scss_test/tree/master

**Comment by JohnAlbin** [comment]
Thanks for the test repo! I'll take a look this week. (or someone can beat me to it and do a PR!)

**Comment by strarsis** [comment]
Awesome, thanks for the fix!
The new release doesn't seem to appear in npm yet, 
I will test it when it becomes available.

**Comment by JohnAlbin** [comment]
It's out. https://www.npmjs.com/package/normalize-scss
