### ISSUE TITLE
Undefined variable: "$px-fallback".

### ISSUE THREAD

**Issue by andrewfleming** [JohnAlbin/normalize-scss#45]
From a fresh Bower install, and import of the normalize.scss files the following error is returned

    Error: Undefined variable: "$px-fallback".
        on line 42 of bower_components/normalize-scss/fork-versions/default/_vertical-rhythm.scss, in `normalize-rhythm'
        from line 58 of bower_components/normalize-scss/fork-versions/default/_vertical-rhythm.scss, in `normalize-margin'
        from line 185 of bower_components/normalize-scss/fork-versions/default/_normalize.scss
        from line 2 of sass/style.scss

**Comment by vwochnik** [comment]
Ha! I have the same problem on my Jekyll installation. Hope someone can fix this.

**Comment by JohnAlbin** [comment]
I'm still trying to work out how the tests for normalize-scss didn't catch this. They should have caught a hard error.

Are you 2 using Ruby Sass or libSass/node-sass ?

**Comment by andrewfleming** [comment]
I'm compiling via [Grunt Contrib Sass](https://github.com/gruntjs/grunt-contrib-sass) which I believe uses Ruby Sass as it's Readme says it's required.

**Comment by JohnAlbin** [comment]
Yeah, the tests are using node-sass. Guh. It must have a scoping bug where it doesn't match the Ruby implementation. Sorry about that!

I'll roll a 4.0.3 version as soon as I fix #47.

**Comment by vwochnik** [comment]
Well, you have fixed #47, can you please bump up the versions so I can get rid of my workaround?

**Comment by vwochnik** [comment]
@JohnAlbin btw why is this a fork of normalize.css? I've looked at it the repository is completely different. I would suggest detaching the fork.

> To detach the fork and turn it into a standalone repository on GitHub, contact [GitHub support](https://github.com/contact).
> 
> -- GitHub Help

**Comment by vwochnik** [comment]
I am using Ruby Sass. I assume that @andrewfleming is using libsass or node-sass based on the stack trace above.

**Comment by JohnAlbin** [comment]
> btw why is this a fork of normalize.css

Well, it _is_ a fork of normalize.css. The last time there was a release of normalize.css, I just merged the commits into this repo.

Does it matter? I can do the merging of the commits regardless of whether it says "forked from necolas/normalize.css" at the top of the page or not.

> can you please bump up the versions so I can get rid of my workaround?

Done!
