### ISSUE TITLE
broken bower.json

### ISSUE THREAD

**Issue by alwin-rewedigital** [JohnAlbin/normalize-scss#52]
Hi,

maybe I'm completely lost, but when I look at your bower.json the normalize/_import-now.scss file is marked as main file.

There are some instructions on how to use your lib, but there is no real scenario on how to use it with bower, except of the note that you have to override some things to use it with wiredep.

We want to use css libs from our project by just running `bower install` and adding an `@import` line in our main css.

In your case, the main file is in the `./normalize` Folder. Normally other css libraries use the main file in the root namespace but you don't, so we can't use your Project in the same generic way with Sass include paths.

If there is nothing against from your side using the `normalize-scss/sass/_normalize.scss` instead of `normalize-scss/sass/normalize/_import-now.scss` you'd help us and properly all wiredeps user as well.

If you agree to that, I can open a PR.

Greets
`Alwin Mark

**Comment by JohnAlbin** [comment]
> Normally other css libraries use the main file in the root namespace but you don't

Ruby Sass will render any Sass files found anywhere in the project if you put your main Sass file in the root. So it becomes impossible to bundle documentation or example projects that may have Sass files in them too.

I've never seen a Sass project put their main file in the project root. e.g. Bootstrap does it similarly: https://github.com/twbs/bootstrap-sass/blob/master/bower.json So you'd need to add `bower_components/bootstrap-sass/assets/stylesheets` to your import paths.

> we can't use your Project in the same generic way with Sass include paths.

Can you be more specific about your generic method? I don't see how normalize-scss having its main file be `sass/normalize/_import-now.scss` makes it harder to set up the import path of `bower_components/normalize-scss/sass`.

**Comment by JohnAlbin** [comment]
> There are some instructions on how to use your lib, but there is no real scenario on how to use it with bower, except of the note that you have to override some things to use it with wiredep.

I use npm to package my Sass. Since I don't use Bower for that task, I would love to have someone provide instructions on a "normal way" to use normalize-scss with Bower. I have the wiredep instructions on the README because someone provided them. :-)

**Comment by alwin-rewedigital** [comment]
It's a namespace issue. Let me explain it in detail:

Bower is capable of main files, so in your build process, you can bower provide you any main files of any project. (With some filtering you can than choose for example which filetype you want). There are different Grunt/Gulp Tasks which are doing that in a similar way.

## the Problem

Currently (@master) the bower main file points to: [sass/normalize/_import-now.scss](https://github.com/JohnAlbin/normalize-scss/blob/master/bower.json#L5).
Basically that's ok so far.
The problem occurs because of namespacing issues, as `_import-now.scss` is doing following imports:

```
@import 'normalize';
```
Now that tells the sass compiler to search for a `normalize.scss` in the same directory as `_import-now.scss`, which is `sass/normalize/normalize.scss`.
Here is the Problem, as normalize.scss is at the folder above.

## Explaining my solution:

As I then took a look at the [_normalize.scss](https://github.com/JohnAlbin/normalize-scss/blob/master/sass/_normalize.scss) I thought this is a way better main file.

1. this file uses the namespace in a way I can use it with bower. (So the main File is in the root of the sass namespace)
2. it does not force me to do a `@include normalize();` so I can print it at my wish.

## Other solutions that (might) would work for me

### moving `_import-now.scss` into the `sass` folder

### using `@import ../normalize` in `_import-now.scss` (I would have to test that first) 


---

I don't know who is also using bower with normalize-scss, but while rethinking everything, maybe moving the `_import-now.scss` file would be the less invasive solution.

**Comment by JohnAlbin** [comment]
Hmm… If there are various gulp/grunt modules that can import the main file from bower.json, then most of those users would not want to use the normalize/import-now partial that renders the CSS immediately; they probably just want the mixins.

Okay, I'm going to make the _normalize.scss the default main file. And also change the path in _import-now.scss to use a `../`

**Comment by JohnAlbin** [comment]
I merged #53
