### ISSUE TITLE
Difference of normalize.css and normalize_scss

### ISSUE THREAD

**Issue by pcabello** [JohnAlbin/normalize-scss#54]
Hi, I'm doing research about what is the best reset css nowadays, and I noticed that a lot of coworkers has been using your normalize_scss while other are using normalize.css from Nicolas. I would like to know what is the difference between your and Nicolas, and if there are some advantage to use the normalize in sass, like performance, or other reasons ?

Thanks Regards

**Comment by JohnAlbin** [comment]
Normalize.css is the original CSS version of the project. If you want to include its CSS in your CSS or Sass project as-is, you should just use normalize.css directly.

If you want control over which browsers are supported by the normalization rules, then normalize-scss has a way to specify the supported browsers. It also has a bunch of other features mentioned on the homepage. https://github.com/JohnAlbin/normalize-scss#how-to-use-it
