### ISSUE TITLE
Conflicts with compass-normalize?

### ISSUE THREAD

**Issue by adi518** [JohnAlbin/normalize-scss#57]
Hi,

I was using [Compass-normalize](https://github.com/ksmandersen/compass-normalize) in an old project. When I was looking for a normalize component, I inadvertently skipped this one and went with the first. For a new project though, I wanted to make sure I'm using this repo, as it's maintained and updated frequently (Compass-normalize is a few years old without any recent updates). So I switched the require statement in config.rb from 'compass-normalize' to 'normalize-scss' and figured I'm good to go. Then, a closer look at my css output, reveals a horrible bug (or feature?). The css output remains that of "compass-normalize". I enabled source comments to find out where the css emits from, and it's most definitely coming from gems/compass-normalize. I have no idea why it does that when I altered my require statement. It seems like uninstalling 'compass-normalize' fixes it, but I cannot uninstall it, as it's a dependency in some of my older projects.

Anyone moving from that old normalize repo to this repo, read the usage instructions carefully. While the old one requires a simple import statement 'import "normalize"', this one requires another line "include normalize()" which of course, calls a mixin. I also didn't notice 'support-for' is required, since I simply switched the require statement and my code compiled just fine. It's up until I noticed the css output is that of "compass-normalize".

Any solution or just a compass bug?

Thanks.

**Comment by JohnAlbin** [comment]
I suspect that you aren't using Bundler. Bundler allows you to manage your Ruby Gem dependencies _per project_. That's crucial when different project require different versions of a Gem. And I suspect it will fix the problem of compass-normalize and normalize-scss having a _normalize.scss partial.

http://bundler.io/rationale.html

**Comment by adi518** [comment]
Thanks, I'll try that.

**Comment by adi518** [comment]
Ok, Bundler indeed solves the problem. Since I'm using Grunt to watch my sass files, I had to pass 'bundleExec: true' to contrib-compass. :)
