### ISSUE TITLE
`line-height` should be unitless

### ISSUE THREAD

**Issue by faddee** [JohnAlbin/normalize-scss#97]
You [convert `line-height` to ems](https://github.com/JohnAlbin/normalize-scss/blob/master/sass/normalize/_normalize-mixin.scss#L65) which result in some [unexpected behavior](https://developer.mozilla.org/en/docs/Web/CSS/line-height#Prefer_unitless_numbers_for_line-height_values). The recommendation is to use unitless values. Is there any reason you chose to convert to ems?

**Comment by JohnAlbin** [comment]
That is only done when the `$normalize-vertical-rhythm` is set to `true`. So if the user wants a vertical rhythm, it will set line-heights in ems (on the html element) and in rems on other elements.

However, I'm now wondering if this bit of code too-aggressively turns on this feature.

```sass
// If we've customized any font variables, we'll need extra properties.
  @if $base-font-size != 16px
    or $base-line-height != 24px
    or $base-unit != 'em'
    or $h1-font-size != 2    * $base-font-size
    or $h2-font-size != 1.5  * $base-font-size
    or $h3-font-size != 1.17 * $base-font-size
    or $h4-font-size != 1    * $base-font-size
    or $h5-font-size != 0.83 * $base-font-size
    or $h6-font-size != 0.67 * $base-font-size {
    $normalize-vertical-rhythm: true !global;
  }
```

You should be able to change $base-font-size and $h1-font-size without triggering the vertical rhythm feature. But all the other variables listed above are only needed if you want a vertical rhythm.
